# Let's Do some Exploratory Data Analysis

<a name="1"> </a>
# 1. Load Dataset

In [2]:
from ipython_secrets import *

data_path = get_secret("data_path")
print(f"DataPath has {len(data)} characters")

DataPath has 80 characters

In [3]:
import pandas as pd

housing_df = pd.read_csv(f"{data_path}")
housing_df.head(10)

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,1,526301100,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900
5,6,527105030,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,6,2010,WD,Normal,195500
6,7,527127150,120,RL,41.0,4920,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,213500
7,8,527145080,120,RL,43.0,5005,Pave,NaN,IR1,HLS,...,0,NaN,NaN,NaN,0,1,2010,WD,Normal,191500
8,9,527146030,120,RL,39.0,5389,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,3,2010,WD,Normal,236500
9,10,527162130,60,RL,60.0,7500,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,6,2010,WD,Normal,189000

<a name="1.1"></a>

## 1.1 Fix column names

In [4]:
# Make column names lowercase
housing_df.columns = map(str.lower, housing_df.columns)

# Remove spaces in column names and Replace them with underscore
housing_df.columns = housing_df.columns.str.replace(' ','_').str.strip()

# View all columns without trubcation
pd.set_option('display.max_columns', None)

# View first 5 items
housing_df.head()

,order,pid,ms_subclass,ms_zoning,lot_frontage,lot_area,street,alley,lot_shape,land_contour,utilities,lot_config,land_slope,neighborhood,condition_1,condition_2,bldg_type,house_style,overall_qual,overall_cond,year_built,year_remod/add,roof_style,roof_matl,exterior_1st,exterior_2nd,mas_vnr_type,mas_vnr_area,exter_qual,exter_cond,foundation,bsmt_qual,bsmt_cond,bsmt_exposure,bsmtfin_type_1,bsmtfin_sf_1,bsmtfin_type_2,bsmtfin_sf_2,bsmt_unf_sf,total_bsmt_sf,heating,heating_qc,central_air,electrical,1st_flr_sf,2nd_flr_sf,low_qual_fin_sf,gr_liv_area,bsmt_full_bath,bsmt_half_bath,full_bath,half_bath,bedroom_abvgr,kitchen_abvgr,kitchen_qual,totrms_abvgrd,functional,fireplaces,fireplace_qu,garage_type,garage_yr_blt,garage_finish,garage_cars,garage_area,garage_qual,garage_cond,paved_drive,wood_deck_sf,open_porch_sf,enclosed_porch,3ssn_porch,screen_porch,pool_area,pool_qc,fence,misc_feature,misc_val,mo_sold,yr_sold,sale_type,sale_condition,saleprice
0,1,526301100,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,6,5,1960,1960,Hip,CompShg,BrkFace,Plywood,Stone,112.0,TA,TA,CBlock,TA,Gd,Gd,BLQ,639.0,Unf,0.0,441.0,1080.0,GasA,Fa,Y,SBrkr,1656,0,0,1656,1.0,0.0,1,0,3,1,TA,7,Typ,2,Gd,Attchd,1960.0,Fin,2.0,528.0,TA,TA,P,210,62,0,0,0,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Feedr,Norm,1Fam,1Story,5,6,1961,1961,Gable,CompShg,VinylSd,VinylSd,NaN,0.0,TA,TA,CBlock,TA,TA,No,Rec,468.0,LwQ,144.0,270.0,882.0,GasA,TA,Y,SBrkr,896,0,0,896,0.0,0.0,1,0,2,1,TA,5,Typ,0,NaN,Attchd,1961.0,Unf,1.0,730.0,TA,TA,Y,140,0,0,0,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,6,6,1958,1958,Hip,CompShg,Wd Sdng,Wd Sdng,BrkFace,108.0,TA,TA,CBlock,TA,TA,No,ALQ,923.0,Unf,0.0,406.0,1329.0,GasA,TA,Y,SBrkr,1329,0,0,1329,0.0,0.0,1,1,3,1,Gd,6,Typ,0,NaN,Attchd,1958.0,Unf,1.0,312.0,TA,TA,Y,393,36,0,0,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,7,5,1968,1968,Hip,CompShg,BrkFace,BrkFace,NaN,0.0,Gd,TA,CBlock,TA,TA,No,ALQ,1065.0,Unf,0.0,1045.0,2110.0,GasA,Ex,Y,SBrkr,2110,0,0,2110,1.0,0.0,2,1,3,1,Ex,8,Typ,2,TA,Attchd,1968.0,Fin,2.0,522.0,TA,TA,Y,0,0,0,0,0,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,5,5,1997,1998,Gable,CompShg,VinylSd,VinylSd,NaN,0.0,TA,TA,PConc,Gd,TA,No,GLQ,791.0,Unf,0.0,137.0,928.0,GasA,Gd,Y,SBrkr,928,701,0,1629,0.0,0.0,2,1,3,1,TA,6,Typ,1,TA,Attchd,1997.0,Fin,2.0,482.0,TA,TA,Y,212,34,0,0,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900

<a name="2"></a>

# 2. EDA

<a name="2.1"></a>
## 2.1 Shape of the data

In [5]:
print(f'Shape of Housing Data: {housing_df.shape}')

Shape of Housing Data: (2930, 82)

**Let's Remove some unnecessary comlums**

In [6]:
# Make 'order' as a index column
housing_df.set_index('order', inplace=True)

# Remove 'pid' column as it's seems to be unnecessary
# housing_df.drop('pid', axis=1, inplace=True)

housing_df.head()

,pid,ms_subclass,ms_zoning,lot_frontage,lot_area,street,alley,lot_shape,land_contour,utilities,lot_config,land_slope,neighborhood,condition_1,condition_2,bldg_type,house_style,overall_qual,overall_cond,year_built,year_remod/add,roof_style,roof_matl,exterior_1st,exterior_2nd,mas_vnr_type,mas_vnr_area,exter_qual,exter_cond,foundation,bsmt_qual,bsmt_cond,bsmt_exposure,bsmtfin_type_1,bsmtfin_sf_1,bsmtfin_type_2,bsmtfin_sf_2,bsmt_unf_sf,total_bsmt_sf,heating,heating_qc,central_air,electrical,1st_flr_sf,2nd_flr_sf,low_qual_fin_sf,gr_liv_area,bsmt_full_bath,bsmt_half_bath,full_bath,half_bath,bedroom_abvgr,kitchen_abvgr,kitchen_qual,totrms_abvgrd,functional,fireplaces,fireplace_qu,garage_type,garage_yr_blt,garage_finish,garage_cars,garage_area,garage_qual,garage_cond,paved_drive,wood_deck_sf,open_porch_sf,enclosed_porch,3ssn_porch,screen_porch,pool_area,pool_qc,fence,misc_feature,misc_val,mo_sold,yr_sold,sale_type,sale_condition,saleprice
order,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,526301100,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,6,5,1960,1960,Hip,CompShg,BrkFace,Plywood,Stone,112.0,TA,TA,CBlock,TA,Gd,Gd,BLQ,639.0,Unf,0.0,441.0,1080.0,GasA,Fa,Y,SBrkr,1656,0,0,1656,1.0,0.0,1,0,3,1,TA,7,Typ,2,Gd,Attchd,1960.0,Fin,2.0,528.0,TA,TA,P,210,62,0,0,0,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
2,526350040,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Feedr,Norm,1Fam,1Story,5,6,1961,1961,Gable,CompShg,VinylSd,VinylSd,NaN,0.0,TA,TA,CBlock,TA,TA,No,Rec,468.0,LwQ,144.0,270.0,882.0,GasA,TA,Y,SBrkr,896,0,0,896,0.0,0.0,1,0,2,1,TA,5,Typ,0,NaN,Attchd,1961.0,Unf,1.0,730.0,TA,TA,Y,140,0,0,0,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
3,526351010,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,6,6,1958,1958,Hip,CompShg,Wd Sdng,Wd Sdng,BrkFace,108.0,TA,TA,CBlock,TA,TA,No,ALQ,923.0,Unf,0.0,406.0,1329.0,GasA,TA,Y,SBrkr,1329,0,0,1329,0.0,0.0,1,1,3,1,Gd,6,Typ,0,NaN,Attchd,1958.0,Unf,1.0,312.0,TA,TA,Y,393,36,0,0,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
4,526353030,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,7,5,1968,1968,Hip,CompShg,BrkFace,BrkFace,NaN,0.0,Gd,TA,CBlock,TA,TA,No,ALQ,1065.0,Unf,0.0,1045.0,2110.0,GasA,Ex,Y,SBrkr,2110,0,0,2110,1.0,0.0,2,1,3,1,Ex,8,Typ,2,TA,Attchd,1968.0,Fin,2.0,522.0,TA,TA,Y,0,0,0,0,0,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
5,527105010,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,5,5,1997,1998,Gable,CompShg,VinylSd,VinylSd,NaN,0.0,TA,TA,PConc,Gd,TA,No,GLQ,791.0,Unf,0.0,137.0,928.0,GasA,Gd,Y,SBrkr,928,701,0,1629,0.0,0.0,2,1,3,1,TA,6,Typ,1,TA,Attchd,1997.0,Fin,2.0,482.0,TA,TA,Y,212,34,0,0,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900

<a name="2.2"></a>

## 2.2 Concise Summary

In [7]:
print(f'Concise Summary of Housing Dataframe:\n{housing_df.info()}')

<class 'pandas.core.frame.DataFrame'>
Index: 2930 entries, 1 to 2930
Data columns (total 81 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pid              2930 non-null   int64
 1   ms_subclass      2930 non-null   int64
 2   ms_zoning        2930 non-null   object
 3   lot_frontage     2440 non-null   float64
 4   lot_area         2930 non-null   int64
 5   street           2930 non-null   object
 6   alley            198 non-null    object
 7   lot_shape        2930 non-null   object
 8   land_contour     2930 non-null   object
 9   utilities        2930 non-null   object
 10  lot_config       2930 non-null   object
 11  land_slope       2930 non-null   object
 12  neighborhood     2930 non-null   object
 13  condition_1      2930 non-null   object
 14  condition_2      2930 non-null   object
 15  bldg_type        2930 non-null   object
 16  house_style      2930 non-null   object
 17  overall_qual     2930 non-null   int64
 18  overall_cond     2930 non-null   int64
 19  year_built       2930 non-null   int64
 20  year_remod/add   2930 non-null   int64
 21  roof_style       2930 non-null   object
 22  roof_matl        2930 non-null   object
 23  exterior_1st     2930 non-null   object
 24  exterior_2nd     2930 non-null   object
 25  mas_vnr_type     1155 non-null   object
 26  mas_vnr_area     2907 non-null   float64
 27  exter_qual       2930 non-null   object
 28  exter_cond       2930 non-null   object
 29  foundation       2930 non-null   object
 30  bsmt_qual        2850 non-null   object
 31  bsmt_cond        2850 non-null   object
 32  bsmt_exposure    2847 non-null   object
 33  bsmtfin_type_1   2850 non-null   object
 34  bsmtfin_sf_1     2929 non-null   float64
 35  bsmtfin_type_2   2849 non-null   object
 36  bsmtfin_sf_2     2929 non-null   float64
 37  bsmt_unf_sf      2929 non-null   float64
 38  total_bsmt_sf    2929 non-null   float64
 39  heating          2930 non-null   object
 40  heating_qc       2930 non-null   object
 41  central_air      2930 non-null   object
 42  electrical       2929 non-null   object
 43  1st_flr_sf       2930 non-null   int64
 44  2nd_flr_sf       2930 non-null   int64
 45  low_qual_fin_sf  2930 non-null   int64
 46  gr_liv_area      2930 non-null   int64
 47  bsmt_full_bath   2928 non-null   float64
 48  bsmt_half_bath   2928 non-null   float64
 49  full_bath        2930 non-null   int64
 50  half_bath        2930 non-null   int64
 51  bedroom_abvgr    2930 non-null   int64
 52  kitchen_abvgr    2930 non-null   int64
 53  kitchen_qual     2930 non-null   object
 54  totrms_abvgrd    2930 non-null   int64
 55  functional       2930 non-null   object
 56  fireplaces       2930 non-null   int64
 57  fireplace_qu     1508 non-null   object
 58  garage_type      2773 non-null   object
 59  garage_yr_blt    2771 non-null   float64
 60  garage_finish    2771 non-null   object
 61  garage_cars      2929 non-null   float64
 62  garage_area      2929 non-null   float64
 63  garage_qual      2771 non-null   object
 64  garage_cond      2771 non-null   object
 65  paved_drive      2930 non-null   object
 66  wood_deck_sf     2930 non-null   int64
 67  open_porch_sf    2930 non-null   int64
 68  enclosed_porch   2930 non-null   int64
 69  3ssn_porch       2930 non-null   int64
 70  screen_porch     2930 non-null   int64
 71  pool_area        2930 non-null   int64
 72  pool_qc          13 non-null     object
 73  fence            572 non-null    object
 74  misc_feature     106 non-null    object
 75  misc_val         2930 non-null   int64
 76  mo_sold          2930 non-null   int64
 77  yr_sold          2930 non-null   int64
 78  sale_type        2930 non-null   object
 79  sale_condition   2930 non-null   object
 80  saleprice        2930 non-null   int64
dtypes: float64(11), int64(27), object(43)
memory usage: 1.8+ MB
Concise Summary of Housing Dataframe:
None

<a name="2.3"></a>

## 2.3 Summary Statistics

In [22]:
# from tabulate import tabulate     # Library to print output in tabular format

# print("Summary Statistics for Housing Dataframe:\n")
# print(tabulate(housing_df.describe(), headers='keys', tablefmt='fancy_grid'))
housing_df.describe()

,pid,ms_subclass,lot_frontage,lot_area,overall_qual,overall_cond,year_built,year_remod/add,mas_vnr_area,bsmtfin_sf_1,bsmtfin_sf_2,bsmt_unf_sf,total_bsmt_sf,1st_flr_sf,2nd_flr_sf,low_qual_fin_sf,gr_liv_area,bsmt_full_bath,bsmt_half_bath,full_bath,half_bath,bedroom_abvgr,kitchen_abvgr,totrms_abvgrd,fireplaces,garage_yr_blt,garage_cars,garage_area,wood_deck_sf,open_porch_sf,enclosed_porch,3ssn_porch,screen_porch,pool_area,misc_val,mo_sold,yr_sold,saleprice
count,2.930000e+03,2930.000000,2440.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2907.000000,2929.000000,2929.000000,2929.000000,2929.000000,2930.000000,2930.000000,2930.000000,2930.000000,2928.000000,2928.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2771.000000,2929.000000,2929.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000
mean,7.144645e+08,57.387372,69.224590,10147.921843,6.094881,5.563140,1971.356314,1984.266553,101.896801,442.629566,49.722431,559.262547,1051.614544,1159.557679,335.455973,4.676792,1499.690444,0.431352,0.061134,1.566553,0.379522,2.854266,1.044369,6.443003,0.599317,1978.132443,1.766815,472.819734,93.751877,47.533447,23.011604,2.592491,16.002048,2.243345,50.635154,6.216041,2007.790444,180796.060068
std,1.887308e+08,42.638025,23.365335,7880.017759,1.411026,1.111537,30.245361,20.860286,179.112611,455.590839,169.168476,439.494153,440.615067,391.890885,428.395715,46.310510,505.508887,0.524820,0.245254,0.552941,0.502629,0.827731,0.214076,1.572964,0.647921,25.528411,0.760566,215.046549,126.361562,67.483400,64.139059,25.141331,56.087370,35.597181,566.344288,2.714492,1.316613,79886.692357
min,5.263011e+08,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,0.000000,0.000000,0.000000,334.000000,0.000000,0.000000,334.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,1895.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,12789.000000
25%,5.284770e+08,20.000000,58.000000,7440.250000,5.000000,5.000000,1954.000000,1965.000000,0.000000,0.000000,0.000000,219.000000,793.000000,876.250000,0.000000,0.000000,1126.000000,0.000000,0.000000,1.000000,0.000000,2.000000,1.000000,5.000000,0.000000,1960.000000,1.000000,320.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,2007.000000,129500.000000
50%,5.354536e+08,50.000000,68.000000,9436.500000,6.000000,5.000000,1973.000000,1993.000000,0.000000,370.000000,0.000000,466.000000,990.000000,1084.000000,0.000000,0.000000,1442.000000,0.000000,0.000000,2.000000,0.000000,3.000000,1.000000,6.000000,1.000000,1979.000000,2.000000,480.000000,0.000000,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,160000.000000
75%,9.071811e+08,70.000000,80.000000,11555.250000,7.000000,6.000000,2001.000000,2004.000000,164.000000,734.000000,0.000000,802.000000,1302.000000,1384.000000,703.750000,0.000000,1742.750000,1.000000,0.000000,2.000000,1.000000,3.000000,1.000000,7.000000,1.000000,2002.000000,2.000000,576.000000,168.000000,70.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,213500.000000
max,1.007100e+09,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,1526.000000,2336.000000,6110.000000,5095.000000,2065.000000,1064.000000,5642.000000,3.000000,2.000000,4.000000,2.000000,8.000000,3.000000,15.000000,4.000000,2207.000000,5.000000,1488.000000,1424.000000,742.000000,1012.000000,508.000000,576.000000,800.000000,17000.000000,12.000000,2010.000000,755000.000000

In [23]:
housing_df.columns

Index(['pid', 'ms_subclass', 'ms_zoning', 'lot_frontage', 'lot_area', 'street',
       'alley', 'lot_shape', 'land_contour', 'utilities', 'lot_config',
       'land_slope', 'neighborhood', 'condition_1', 'condition_2', 'bldg_type',
       'house_style', 'overall_qual', 'overall_cond', 'year_built',
       'year_remod/add', 'roof_style', 'roof_matl', 'exterior_1st',
       'exterior_2nd', 'mas_vnr_type', 'mas_vnr_area', 'exter_qual',
       'exter_cond', 'foundation', 'bsmt_qual', 'bsmt_cond', 'bsmt_exposure',
       'bsmtfin_type_1', 'bsmtfin_sf_1', 'bsmtfin_type_2', 'bsmtfin_sf_2',
       'bsmt_unf_sf', 'total_bsmt_sf', 'heating', 'heating_qc', 'central_air',
       'electrical', '1st_flr_sf', '2nd_flr_sf', 'low_qual_fin_sf',
       'gr_liv_area', 'bsmt_full_bath', 'bsmt_half_bath', 'full_bath',
       'half_bath', 'bedroom_abvgr', 'kitchen_abvgr', 'kitchen_qual',
       'totrms_abvgrd', 'functional', 'fireplaces', 'fireplace_qu',
       'garage_type', 'garage_yr_blt', 'garage_finish', 'garage_cars',
       'garage_area', 'garage_qual', 'garage_cond', 'paved_drive',
       'wood_deck_sf', 'open_porch_sf', 'enclosed_porch', '3ssn_porch',
       'screen_porch', 'pool_area', 'pool_qc', 'fence', 'misc_feature',
       'misc_val', 'mo_sold', 'yr_sold', 'sale_type', 'sale_condition',
       'saleprice'],
      dtype='object')

**Check For Unique Values in columns**

In [21]:
for column in housing_df.columns:
    unique_value = housing_df[column].nunique()
    column_dtype = housing_df[column].dtype
    print(f"Unique values in Column    {column} : {unique_value} \n Datatype: {column_dtype}")

Unique values in Column    pid : 2930
 Datatype: int64
Unique values in Column    ms_subclass : 16
 Datatype: int64
Unique values in Column    ms_zoning : 7
 Datatype: object
Unique values in Column    lot_frontage : 128
 Datatype: float64
Unique values in Column    lot_area : 1960
 Datatype: int64
Unique values in Column    street : 2
 Datatype: object
Unique values in Column    alley : 2
 Datatype: object
Unique values in Column    lot_shape : 4
 Datatype: object
Unique values in Column    land_contour : 4
 Datatype: object
Unique values in Column    utilities : 3
 Datatype: object
Unique values in Column    lot_config : 5
 Datatype: object
Unique values in Column    land_slope : 3
 Datatype: object
Unique values in Column    neighborhood : 28
 Datatype: object
Unique values in Column    condition_1 : 9
 Datatype: object
Unique values in Column    condition_2 : 8
 Datatype: object
Unique values in Column    bldg_type : 5
 Datatype: object
Unique values in Column    house_style : 8
 Datatype: object
Unique values in Column    overall_qual : 10
 Datatype: int64
Unique values in Column    overall_cond : 9
 Datatype: int64
Unique values in Column    year_built : 118
 Datatype: int64
Unique values in Column    year_remod/add : 61
 Datatype: int64
Unique values in Column    roof_style : 6
 Datatype: object
Unique values in Column    roof_matl : 8
 Datatype: object
Unique values in Column    exterior_1st : 16
 Datatype: object
Unique values in Column    exterior_2nd : 17
 Datatype: object
Unique values in Column    mas_vnr_type : 4
 Datatype: object
Unique values in Column    mas_vnr_area : 445
 Datatype: float64
Unique values in Column    exter_qual : 4
 Datatype: object
Unique values in Column    exter_cond : 5
 Datatype: object
Unique values in Column    foundation : 6
 Datatype: object
Unique values in Column    bsmt_qual : 5
 Datatype: object
Unique values in Column    bsmt_cond : 5
 Datatype: object
Unique values in Column    bsmt_exposure : 4
 Datatype: object
Unique values in Column    bsmtfin_type_1 : 6
 Datatype: object
Unique values in Column    bsmtfin_sf_1 : 995
 Datatype: float64
Unique values in Column    bsmtfin_type_2 : 6
 Datatype: object
Unique values in Column    bsmtfin_sf_2 : 274
 Datatype: float64
Unique values in Column    bsmt_unf_sf : 1137
 Datatype: float64
Unique values in Column    total_bsmt_sf : 1058
 Datatype: float64
Unique values in Column    heating : 6
 Datatype: object
Unique values in Column    heating_qc : 5
 Datatype: object
Unique values in Column    central_air : 2
 Datatype: object
Unique values in Column    electrical : 5
 Datatype: object
Unique values in Column    1st_flr_sf : 1083
 Datatype: int64
Unique values in Column    2nd_flr_sf : 635
 Datatype: int64
Unique values in Column    low_qual_fin_sf : 36
 Datatype: int64
Unique values in Column    gr_liv_area : 1292
 Datatype: int64
Unique values in Column    bsmt_full_bath : 4
 Datatype: float64
Unique values in Column    bsmt_half_bath : 3
 Datatype: float64
Unique values in Column    full_bath : 5
 Datatype: int64
Unique values in Column    half_bath : 3
 Datatype: int64
Unique values in Column    bedroom_abvgr : 8
 Datatype: int64
Unique values in Column    kitchen_abvgr : 4
 Datatype: int64
Unique values in Column    kitchen_qual : 5
 Datatype: object
Unique values in Column    totrms_abvgrd : 14
 Datatype: int64
Unique values in Column    functional : 8
 Datatype: object
Unique values in Column    fireplaces : 5
 Datatype: int64
Unique values in Column    fireplace_qu : 5
 Datatype: object
Unique values in Column    garage_type : 6
 Datatype: object
Unique values in Column    garage_yr_blt : 103
 Datatype: float64
Unique values in Column    garage_finish : 3
 Datatype: object
Unique values in Column    garage_cars : 6
 Datatype: float64
Unique values in Column    garage_area : 603
 Datatype: float64
Unique values in Column    garage_qual : 5
 Datatype: object
Unique values in Column    garage_cond : 5
 Datatype: object
Unique values in Column    paved_drive : 3
 Datatype: object
Unique values in Column    wood_deck_sf : 380
 Datatype: int64
Unique values in Column    open_porch_sf : 252
 Datatype: int64
Unique values in Column    enclosed_porch : 183
 Datatype: int64
Unique values in Column    3ssn_porch : 31
 Datatype: int64
Unique values in Column    screen_porch : 121
 Datatype: int64
Unique values in Column    pool_area : 14
 Datatype: int64
Unique values in Column    pool_qc : 4
 Datatype: object
Unique values in Column    fence : 4
 Datatype: object
Unique values in Column    misc_feature : 5
 Datatype: object
Unique values in Column    misc_val : 38
 Datatype: int64
Unique values in Column    mo_sold : 12
 Datatype: int64
Unique values in Column    yr_sold : 5
 Datatype: int64
Unique values in Column    sale_type : 10
 Datatype: object
Unique values in Column    sale_condition : 6
 Datatype: object
Unique values in Column    saleprice : 1032
 Datatype: int64

**Dataset Description**

- `lot_frontage`: Linear feet of street connected to property
- `lot_area`: Lot size in square feet
- `overall_qual`: Overall material and finish quality
- `overall_cond`: Overall condition rating
- `year_built`: Original construction date
- `year_remod/add`: Remodel date (same as construction date if no remodeling or additions)
- `mas_vnr_area`: Masonry veneer area in square feet
- `bsmtfin_sf_1`: Type 1 finished square feet
- `bsmtfin_sf_2`: Type 2 finished square feet
- `bsmt_unf_sf`: Unfinished square feet of basement area
- `total_bsmt_sf`: Total square feet of basement area
- `1st_flr_sf`: First Floor square feet
- `2nd_flr_sf`: Second floor square feet
- `low_qual_fin_sf`: Low quality finished square feet (all floors)
- `gr_liv_area`: Above-grade (ground) living area square feet
- `bsmt_full_bath`: Basement full bathrooms
- `bsmt_half_bath`: Basement half bathrooms
- `full_bath`: Full bathrooms above grade
- `half_bath`: Half baths above grade
- `bedroom_abvgr`: Bedrooms above grade (does NOT include basement bedrooms)
- `kitchen_abvgr`: Kitchens above grade
- `totrms_abvgrd`: Total rooms above grade (does not include bathrooms)
- `fireplaces`: Number of fireplaces
- `garage_cars`: Size of garage in car capacity
- `garage_area`: Size of garage in square feet
- `wood_deck_sf`: Wood deck area in square feet
- `open_porch_sf`: Open porch area in square feet
- `enclosed_porch`: Enclosed porch area in square feet
- `3ssn_porch`: Three season porch area in square feet
- `screen_porch`: Screen porch area in square feet
- `pool_area`: Pool area in square feet
- `misc_val`: $Value of miscellaneous feature
Categorical Features:

- `ms_zoning`: Zoning classification
- `street`: Type of road access to property
- `alley`: Type of alley access to property
- `lot_shape`: General shape of property
- `land_contour`: Flatness of the property
- `utilities`: Type of utilities available
- `lot_config`: Lot configuration
- `land_slope`: Slope of property
- `neighborhood`: Physical locations within Ames city limits
- `condition_1`: Proximity to various conditions
- `condition_2`: Proximity to various conditions (if more than one is present)
- `bldg_type`: Type of dwelling
- `house_style`: Style of dwelling
- `roof_style`: Type of roof
- `roof_matl`: Roof material
- `exterior_1st`: Exterior covering on house
- `exterior_2nd`: Exterior covering on house (if more than one material)
- `mas_vnr_type`: Masonry veneer type
- `exter_qual`: Exterior material quality
- `exter_cond`: Present condition of the material on the exterior
- `foundation`: Type of foundation
- `bsmt_qual`: Height of the basement
- `bsmt_cond`: General condition of the basement
- `bsmt_exposure`: Walkout or garden level basement walls
- `bsmtfin_type_1`: Quality of basement finished area
- `bsmtfin_type_2`: Quality of second finished area (if present)
- `heating`: Type of heating
- `heating_qc`: Heating quality and condition
- `central_air`: Central air conditioning
- `electrical`: Electrical system
- `kitchen_qual`: Kitchen quality
- `functional`: Home functionality rating
- `fireplace_qu`: Fireplace quality
- `garage_type`: Garage location
- `garage_finish`: Interior finish of the garage
- `garage_qual`: Garage quality
- `garage_cond`: Garage condition
- `paved_drive`: Paved driveway
- `pool_qc`: Pool quality
- `fence`: Fence quality
- `misc_feature`: Miscellaneous feature not covered in other categories
- `sale_type`: Type of sale
- `sale_condition`: Condition of sale